[[task]]
title = "Refine the color scheme & layout"
done = false

[[task]]
title = "Figure out why my CI/CD variables dont populate on Pages"
done = false

[[task]]
title = "write more about plannet (i added it to this project :D)"
done = false
